"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { supabaseBrowser } from "@/lib/supabase-browser";

export default function LoginPage() {
  const [mode, setMode] = useState<"team" | "admin">("team");
  const [teamName, setTeamName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [teamPassword, setTeamPassword] = useState("");
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const router = useRouter();
  async function submit(e: FormEvent) {
    e.preventDefault(); setError(""); setBusy(true);
    try {
      if (mode === "team") {
        const res = await fetch("/api/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ team_name: teamName, password_code: teamPassword }) });
        const data = await res.json(); if (!res.ok) throw new Error(data.error); router.push("/team");
      } else {
        if (process.env.NEXT_PUBLIC_DRY_RUN === "true") {
          const res = await fetch("/api/admin-login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) });
          const data = await res.json(); if (!res.ok) throw new Error(data.error); router.push("/admin");
        } else {
          const { error } = await supabaseBrowser().auth.signInWithPassword({ email, password });
          if (error) throw error; router.push("/admin");
        }
      }
    } catch (e) { setError(e instanceof Error ? e.message : "Could not sign in."); } finally { setBusy(false); }
  }
  return <main className="grain min-h-screen flex items-center justify-center p-5 relative overflow-hidden">
    <div className="absolute w-[560px] h-[560px] rounded-full bg-[#f0444c]/[.035] blur-3xl -top-60 -right-52" />
    <section className="w-full max-w-[430px] relative">
      <div className="flex items-center gap-3 mb-10"><div className="w-10 h-10 rounded-full border border-[#f0444c]/60 flex items-center justify-center text-[#f0444c] text-xl serif">M</div><div><p className="eyebrow !text-[#f0444c]">Dead Air · Recovery desk</p><p className="font-semibold tracking-wide">MERIDIAN / CASE 014</p></div></div>
      <div className="relative h-44 rounded-xl overflow-hidden mb-8 border border-white/10"><img src="/event-poster.png" alt="Dead Air: investigate, solve, uncover" className="w-full h-full object-cover object-[50%_28%]"/><div className="absolute inset-0 bg-gradient-to-t from-[#0d1111] via-transparent to-black/20"/><span className="absolute bottom-3 left-4 eyebrow text-white">LHC214 · 10 October 2026</span></div>
      <p className="eyebrow mb-4">Access terminal <span className="text-[#f0444c]">●</span> {process.env.NEXT_PUBLIC_DRY_RUN === "true" ? "local dry run" : "secure connection"}</p>
      <h1 className="serif text-5xl leading-[1.04] mb-4">The signal<br/><i className="text-[#f0444c]">is still live.</i></h1>
      <p className="text-[#9ba49f] leading-6 mb-9 max-w-sm">{process.env.NEXT_PUBLIC_DRY_RUN === "true" ? "Local rehearsal mode is active. Organizers can create teams and generate access passwords in the control room." : "Your case is waiting. Enter the access code provided by your field coordinator."}</p>
      <div className="panel p-2 flex mb-5"><button onClick={()=>{setMode("team");setError("")}} className={`flex-1 rounded-lg py-3 text-sm ${mode==="team"?"bg-[#252d2b] text-white":"text-[#85908a]"}`}>Team access</button><button onClick={()=>{setMode("admin");setError("")}} className={`flex-1 rounded-lg py-3 text-sm ${mode==="admin"?"bg-[#252d2b] text-white":"text-[#85908a]"}`}>Organizer</button></div>
      <form onSubmit={submit} className="space-y-4">
        {mode === "team" ? <><label className="block"><span className="eyebrow block mb-2">Team name</span><input autoFocus value={teamName} onChange={e=>setTeamName(e.target.value)} placeholder="Enter your registered team name" className="field w-full px-4 py-3" required /></label><label className="block"><span className="eyebrow block mb-2">Team password</span><input type="password" value={teamPassword} onChange={e=>setTeamPassword(e.target.value)} placeholder="Generated by your organizer" className="field w-full px-4 py-3 tracking-wider" required /></label></> : <><label className="block"><span className="eyebrow block mb-2">Admin email</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@organization.org" className="field w-full px-4 py-3" required /></label><label className="block"><span className="eyebrow block mb-2">Password</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} className="field w-full px-4 py-3" required /></label></>}
        {error&&<p role="alert" className="text-sm text-[#ff9270]">{error}</p>}
        <button disabled={busy} className="btn-primary w-full py-4 flex items-center justify-center gap-3">{busy?"Connecting…":mode==="team"?"Talk to Echo":"Enter control room"}<span>↗</span></button>
      </form>
      <div className="mt-12 pt-5 border-t line flex justify-between text-[10px] tracking-[.15em] uppercase text-[#66716c]"><span>Authorized personnel only</span><span>Session encrypted</span></div>
    </section>
  </main>;
}
